server:
  port: ${PORT:8080}

spring:
  application:
    name: deployhub-springboot

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
